/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const v1_cts_invite = t.iface([], {
  "type": t.lit("invite"),
  "groupName": "string",
});

export const v1_cts_get_messages = t.iface([], {
  "type": t.lit("getmessages"),
  "segment": t.union("number", "null", "undefined"),
  "roomid": "RoomUUID",
});

export const v1_cts_message = t.iface([], {
  "type": t.lit("message"),
  "filename": t.union("string", "null"),
  "rawfile": t.union("string", "null"),
  "roomid": "RoomUUID",
  "message": "v1_shared_message_ephemeral",
});

export const v1_cts_join_room = t.iface([], {
  "type": t.lit("joinroom"),
  "roomid": "RoomUUID",
});

export const v1_cts_leave_room = t.iface([], {
  "type": t.lit("leaveroom"),
});

export const v1_cts_video = t.iface([], {
  "type": t.lit("video"),
  "touserid": "UserUUID",
  "payload": "string",
});

export const v1_cts_go_live = t.iface([], {
  "type": t.lit("golive"),
  "livestate": "boolean",
  "livelabel": "string",
});

export const v1_cts_let_me_see = t.iface([], {
  "type": t.lit("letmesee"),
  "touserid": "UserUUID",
  "message": "boolean",
});

export const v1_cts_create_room = t.iface([], {
  "type": t.lit("createroom"),
  "roomType": t.union(t.lit("voice"), t.lit("text")),
  "roomName": "string",
});

export const v1_cts_create_user = t.iface([], {
  "type": t.lit("createuser"),
  "userName": "string",
  "groupName": "string",
  "email": "string",
});

export const v1_cts_update_room = t.iface([], {
  "type": t.lit("updateroom"),
  "roomid": "RoomUUID",
  "roomName": "string",
});

export const v1_cts_update_user = t.iface([], {
  "type": t.lit("updateuser"),
  "userid": "UserUUID",
  "userName": "string",
});

export const v1_cts_remove_room = t.iface([], {
  "type": t.lit("removeroom"),
  "roomid": "RoomUUID",
});

export const v1_cts_remove_user = t.iface([], {
  "type": t.lit("removeuser"),
  "withvengence": "boolean",
  "touserid": "UserUUID",
});

export const v1_cts_update_message = t.iface([], {
  "type": t.lit("updatemessage"),
  "message": "v1_shared_message_update",
});

export const v1_cts_remove_message = t.iface([], {
  "type": t.lit("removemessage"),
  "roomid": "RoomUUID",
  "messageid": "number",
});

export const v1_cts_create_group = t.iface([], {
  "type": t.lit("creategroup"),
  "groupName": "string",
});

export const v1_cts_update_group = t.iface([], {
  "type": t.lit("updategroup"),
  "groupName": "string",
  "changes": t.array("v1_shared_group_change"),
});

export const v1_cts_remove_group = t.iface([], {
  "type": t.lit("removegroup"),
  "groupName": "string",
});

export const v1_cts_set_user_group = t.iface([], {
  "type": t.lit("setusergroup"),
  "userid": "UserUUID",
  "groupName": "string",
});

export const v1_cts_chat_device = t.iface([], {
  "type": t.lit("chatdev"),
  "video": "boolean",
  "audio": "boolean",
});

export const v1_cts_server_mute = t.iface([], {
  "type": t.lit("servermute"),
  "userid": "UserUUID",
  "suppress": "boolean",
});

export const v1_cts_talking = t.iface([], {
  "type": t.lit("talking"),
  "talking": "boolean",
});

export const v1_cts_context_option = t.iface([], {
  "type": t.lit("contextoption"),
  "context": "v1_shared_context_type",
  "option": "string",
  "value": "string",
});

export const v1_cts_window_input = t.iface([], {
  "type": t.lit("windowinput"),
  "inputid": "string",
  "value": "string",
  "allinputs": "string",
});

export const v1_cts_packet = t.union("v1_cts_invite", "v1_cts_get_messages", "v1_cts_message", "v1_cts_join_room", "v1_cts_leave_room", "v1_cts_video", "v1_cts_go_live", "v1_cts_let_me_see", "v1_cts_create_room", "v1_cts_create_user", "v1_cts_update_room", "v1_cts_update_user", "v1_cts_remove_room", "v1_cts_remove_user", "v1_cts_update_message", "v1_cts_remove_message", "v1_cts_create_group", "v1_cts_update_group", "v1_cts_remove_group", "v1_cts_set_user_group", "v1_cts_chat_device", "v1_cts_server_mute", "v1_cts_talking", "v1_cts_context_option", "v1_cts_window_input");

const exportedTypeSuite: t.ITypeSuite = {
  v1_cts_invite,
  v1_cts_get_messages,
  v1_cts_message,
  v1_cts_join_room,
  v1_cts_leave_room,
  v1_cts_video,
  v1_cts_go_live,
  v1_cts_let_me_see,
  v1_cts_create_room,
  v1_cts_create_user,
  v1_cts_update_room,
  v1_cts_update_user,
  v1_cts_remove_room,
  v1_cts_remove_user,
  v1_cts_update_message,
  v1_cts_remove_message,
  v1_cts_create_group,
  v1_cts_update_group,
  v1_cts_remove_group,
  v1_cts_set_user_group,
  v1_cts_chat_device,
  v1_cts_server_mute,
  v1_cts_talking,
  v1_cts_context_option,
  v1_cts_window_input,
  v1_cts_packet,
};
export default exportedTypeSuite;
