/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const v1_stc_login = t.iface([], {
  "type": t.lit("login"),
  "userid": "UserUUID",
  "success": "boolean",
});

export const v1_stc_update_users = t.iface([], {
  "type": t.lit("updateUsers"),
  "userList": t.array("v1_shared_user"),
});

export const v1_stc_update_rooms = t.iface([], {
  "type": t.lit("updateRooms"),
  "roomList": t.array("v1_shared_room"),
});

export const v1_stc_chatdev = t.iface([], {
  "type": t.lit("chatdev"),
  "userid": "UserUUID",
  "video": "boolean",
  "audio": "boolean",
});

export const v1_stc_join_room = t.iface([], {
  "type": t.lit("joinRoom"),
  "userid": "UserUUID",
  "roomid": "RoomUUID",
});

export const v1_stc_update_text = t.iface([], {
  "type": t.lit("updateText"),
  "roomid": "RoomUUID",
  "segment": "number",
  "messages": t.array("v1_shared_message_real"),
});

export const v1_stc_leave_room = t.iface([], {
  "type": t.lit("leaveRoom"),
  "userid": "UserUUID",
  "roomid": "RoomUUID",
});

export const v1_stc_video = t.iface([], {
  "type": t.lit("video"),
  "payload": "unknown",
  "touserid": "UserUUID",
  "fromuserid": "UserUUID",
});

export const v1_stc_update_perms = t.iface([], {
  "type": t.lit("updatePerms"),
  "perms": t.array("string"),
});

export const v1_stc_update_groups = t.iface([], {
  "type": t.lit("updateGroups"),
  "groups": "v1_shared_groups_list",
});

export const v1_stc_invite = t.iface([], {
  "type": t.lit("invite"),
  "invite_code": "string",
});

export const v1_stc_send_message = t.iface([], {
  "type": t.lit("sendMessage"),
  "roomid": "RoomUUID",
  "message": "v1_shared_message_real",
});

export const v1_stc_server_mute = t.iface([], {
  "type": t.lit("servermute"),
  "userid": "UserUUID",
  "message": "boolean",
});

export const v1_stc_talking = t.iface([], {
  "userid": "UserUUID",
  "type": t.lit("talking"),
  "talking": "boolean",
});

export const v1_stc_go_live = t.iface([], {
  "type": t.lit("golive"),
  "livestate": "boolean",
  "livelabel": "string",
  "userid": "UserUUID",
  "roomid": "RoomUUID",
});

export const v1_stc_let_me_see = t.iface([], {
  "type": t.lit("letmesee"),
  "touserid": "UserUUID",
  "fromuserid": "UserUUID",
  "message": "boolean",
});

export const v1_stc_present_custom_window = t.iface([], {
  "type": t.lit("presentcustomwindow"),
  "window": "any",
});

export const v1_stc_disconnect = t.iface([], {
  "type": t.lit("disconnect"),
  "userid": "UserUUID",
});

export const v1_stc_packet = t.union("v1_stc_login", "v1_stc_update_rooms", "v1_stc_update_users", "v1_stc_chatdev", "v1_stc_join_room", "v1_stc_update_text", "v1_stc_leave_room", "v1_stc_video", "v1_stc_update_perms", "v1_stc_update_groups", "v1_stc_invite", "v1_stc_send_message", "v1_stc_server_mute", "v1_stc_talking", "v1_stc_go_live", "v1_stc_let_me_see", "v1_stc_present_custom_window", "v1_stc_disconnect");

const exportedTypeSuite: t.ITypeSuite = {
  v1_stc_login,
  v1_stc_update_users,
  v1_stc_update_rooms,
  v1_stc_chatdev,
  v1_stc_join_room,
  v1_stc_update_text,
  v1_stc_leave_room,
  v1_stc_video,
  v1_stc_update_perms,
  v1_stc_update_groups,
  v1_stc_invite,
  v1_stc_send_message,
  v1_stc_server_mute,
  v1_stc_talking,
  v1_stc_go_live,
  v1_stc_let_me_see,
  v1_stc_present_custom_window,
  v1_stc_disconnect,
  v1_stc_packet,
};
export default exportedTypeSuite;
