/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const v1_shared_message_ephemeral = t.iface([], {
  "url": t.union("string", "null"),
  "text": "string",
  "tags": t.array("string"),
});

export const v1_shared_message_real = t.iface([], {
  "roomid": "RoomUUID",
  "idx": t.union("number", "null"),
  "text": "string",
  "img": t.union("string", "null"),
  "url": t.union("string", "null"),
  "height": t.union("number", "null"),
  "width": t.union("number", "null"),
  "userid": t.union("UserUUID", "null"),
  "tags": t.array("string"),
  "type": t.union("string", "null"),
  "username": "string",
});

export const v1_shared_message_update = t.iface([], {
  "roomid": "RoomUUID",
  "idx": "number",
  "text": t.opt("string"),
  "img": t.opt("string"),
  "url": t.opt("string"),
  "width": t.opt("number"),
  "height": t.opt("number"),
  "userid": t.opt("UserUUID"),
  "tags": t.opt(t.array("string")),
  "type": t.opt("string"),
  "username": t.opt("string"),
});

export const v1_shared_group_change = t.iface([], {
  "add": t.opt("string"),
  "remove": t.opt("string"),
});

export const v1_shared_room = t.iface([], {
  "id": "RoomUUID",
  "type": "string",
  "name": "string",
  "userlist": t.array("v1_shared_user"),
});

export const v1_shared_user = t.iface([], {
  "id": "UserUUID",
  "currentRoom": t.union("RoomUUID", "null"),
  "livestate": "boolean",
  "livelabel": "string",
  "name": "string",
  "talking": "boolean",
  "suppress": "boolean",
  "status": "boolean",
  "avatar": t.union("string", "undefined"),
  "hidden": "boolean",
});

export const v1_shared_context_menu = t.iface([], {
  "label": "string",
  "permissionRequired": "string",
  "option": "string",
});

export const v1_shared_context_menu_collection = t.iface([], {
  "user": t.array("v1_shared_context_menu"),
  "room": t.array("v1_shared_context_menu"),
  "textroom": t.array("v1_shared_context_menu"),
  "voiceroom": t.array("v1_shared_context_menu"),
  "message": t.array("v1_shared_context_menu"),
});

export const v1_shared_groups_list = t.iface([], {
  [t.indexKey]: t.array("string"),
});

export const v1_shared_context_type = t.union(t.lit("user"), t.lit("room"), t.lit("voiceroom"), t.lit("textroom"), t.lit("message"), t.lit("livestream"));

export const UserUUID = t.name("string");

export const RoomUUID = t.name("string");

export const ConnUUID = t.name("string");

const exportedTypeSuite: t.ITypeSuite = {
  v1_shared_message_ephemeral,
  v1_shared_message_real,
  v1_shared_message_update,
  v1_shared_group_change,
  v1_shared_room,
  v1_shared_user,
  v1_shared_context_menu,
  v1_shared_context_menu_collection,
  v1_shared_groups_list,
  v1_shared_context_type,
  UserUUID,
  RoomUUID,
  ConnUUID,
};
export default exportedTypeSuite;
