/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const v0_cts_signup = t.iface([], {
  "type": t.lit("signup"),
  "userName": "string",
  "password": "string",
  "signUp": "string",
  "email": "string",
});

export const v0_cts_login = t.iface([], {
  "type": t.lit("login"),
  "password": "string",
  "protocol": "string",
  "email": "string",
});

export const v0_cts_packet = t.union("v0_cts_login", "v0_cts_signup");

const exportedTypeSuite: t.ITypeSuite = {
  v0_cts_signup,
  v0_cts_login,
  v0_cts_packet,
};
export default exportedTypeSuite;
