/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const v0_stc_connect_packet = t.iface([], {
  "type": t.lit("connect"),
  "message": "string",
  "icon": "string",
  "contextmenus": "v0_shared_context_menu_collection",
  "protocols": t.array("string"),
});

export const v0_stc_error = t.iface([], {
  "type": t.lit("error"),
  "message": "string",
});

export const v0_stc_refresh_now = t.iface([], {
  "type": t.lit("refreshNow"),
});

export const v0_stc_packet = t.union("v0_stc_connect_packet", "v0_stc_error", "v0_stc_refresh_now");

const exportedTypeSuite: t.ITypeSuite = {
  v0_stc_connect_packet,
  v0_stc_error,
  v0_stc_refresh_now,
  v0_stc_packet,
};
export default exportedTypeSuite;
