/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const v0_shared_context_menu = t.iface([], {
  "label": "string",
  "permissionRequired": "string",
  "option": "string",
});

export const v0_shared_context_menu_collection = t.iface([], {
  "user": t.array("v0_shared_context_menu"),
  "room": t.array("v0_shared_context_menu"),
  "textroom": t.array("v0_shared_context_menu"),
  "voiceroom": t.array("v0_shared_context_menu"),
  "message": t.array("v0_shared_context_menu"),
});

const exportedTypeSuite: t.ITypeSuite = {
  v0_shared_context_menu,
  v0_shared_context_menu_collection,
};
export default exportedTypeSuite;
