/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const any_stc_packet = t.union("v0_stc_packet", "v1_stc_packet");

export const any_cts_packet = t.union("v0_cts_packet", "v1_cts_packet");

const exportedTypeSuite: t.ITypeSuite = {
  any_stc_packet,
  any_cts_packet,
};
export default exportedTypeSuite;
